#!/usr/bin/python3
#
# Smart Meter Redis Logger
# Reads mqtt power-log and sends it to Redis Server
# Copyright: Stefan Koch
# License: GPLv3
#

import paho.mqtt.client as mqtt
from   datetime import datetime
import json
import sys
import os

sys.path.append("../rediscon")
from rediscon import RedisCon
from modules.configfile import ConfigFile

script_d = os.path.dirname(os.path.realpath(__file__))
os.chdir(script_d)

print("Smart Meter Redis Logger")

#
# Check for debug mode (use -d)
#
debug = False
if 2 == len(sys.argv):
    cmd_arg = sys.argv[1]
    if cmd_arg == "-d":
        debug = True

#
# open and parse configuration file
# see smlogger.conf-example for examples
#
try:
    conf            = ConfigFile("smlogger.conf")
    mqtt_topic      = conf.get_value("mqtt_topic")
    redis_server    = conf.get_value("redis_server")
    pow_current_key = conf.get_value("power_current_key")
    pow_day_key     = conf.get_value("power_day_key")
    ts_key          = conf.get_value("ts_key")
    update_period   = conf.get_value("update_period")
    avg_window_size = conf.get_value("avg_window_size")
except Exception as e:
    print(e)
    sys.exit(1)

#
# time functions to determine update time and daily usage report
#
def get_ts():
    return int(datetime.now().timestamp())


# turns a hour + minute into a single numerical value
# e.g. 23:30 will become the value 2330
tzone = datetime.now().astimezone().tzinfo
def get_day_mark():
    h = datetime.now(tz=tzone).hour
    m = datetime.now(tz=tzone).minute
    marker = (h * 100) + m
    return  marker


#
# print out important configuration parameters
#
print("-------------------------------")
print("redis_server    = " + str(redis_server))
print("pow_current_key = " + str(pow_current_key))
print("pow_day_key     = " + str(pow_day_key))
print("ts_ke           = " + str(ts_key))
print("mqtt_topic      = " + str(mqtt_topic))
print("update_period   = " + str(update_period))
print("avg_window_size = " + str(avg_window_size))
print("debug           = " + str(debug))
print("-------------------------------")

#
# connect to Redis
# Redis is our outgoing data channel. The redis instance is mostly remote
# you can modify the value keys in the config file
#
print("connect Redis..")
try:
    red = RedisCon(name="powlog", host=redis_server, log_enabled=False, trx_log=debug)
    red.setConMonInterval(5)
    red.connect()
except Exception as e:
    print(e)
    sys.exit(1)
print("OK")

#
# these variables track the two different update moments
#
ts    = get_ts()
last_dm = get_day_mark()
ptot_day_start = 0
first = True

#
# windowing functions to smooth out the current power value
# if your processing/visualization backend does smooting as well then you
# should reduce the window size in the config file
#
val_window = [0] * avg_window_size
def window_insert(v):
    global val_window
    size = len(val_window)

    for i in range(0, size - 1):
        val_window[i] = val_window[i + 1]

    val_window[size - 1] = v


def window_avg():
    size = len(val_window)
    avg  = 0
    for i in range(0, size):
        avg += val_window[i]
    return int(avg / size)


#
# (part of mqtt callback)
# for every mqtt message this functionis executed
# here happens the averaging and time triggered updates to redis
#
def update(data):
    global ts
    global last_dm
    global first
    global ptot_day_start
    p_cur = data['pmon']
    p_tot = data['ptot']

    window_insert(p_cur)
    cur_ts = get_ts()
    cur_dm = get_day_mark()

    # on the first udate we set the total power capture of the day
    # to the current total power counter of the smart meter
    # Note: unless you start this program right after midnight
    #       the total power per day is incomplete for the first day
    if first:
        first = False
        ptot_day_start = p_tot

    if debug:
        print("ts=%d cur_dm=%04d last_dm=%04d p_tot=%d p_cur=%d" % 
            (cur_ts, cur_dm, last_dm, p_tot, p_cur))

    # check if we just crossed the day start (00:00) - if so, reset 
    # the total power capture of the day
    if cur_dm < last_dm:
        ptot_day_start = p_tot
    last_dm = cur_dm

    # check if the update period has been passed - if so, send update
    # and reset timestamp ts
    if (cur_ts - ts) >= update_period:
        red.set(pow_current_key, window_avg())

        ptot_delta = p_tot - ptot_day_start
        # convert from Wh to kWh
        red.set(pow_day_key, float("{0:.2f}".format(ptot_delta/1000)))

        # update value timestamp
        red.set(ts_key, cur_ts)

        ts = cur_ts


#
# (mqtt callback)
# connection indicator, were we subscribe to the powlog mqtt topic
#
def mqtt_connect(client, userdata, flags, rc):
    print("OK " + str(rc))
    client.subscribe(mqtt_topic)

#
# (mqtt callback)
# called for every message on mqtt topic
# here we convert the json to python-dictionary
# any conversion error leads to ignore the message
#
def mqtt_message(client, userdata, msg):
    if (mqtt_topic == msg.topic):
        try:
            data = json.loads(msg.payload.decode("utf-8"))
        except:
            print("error json decode")
            print(str(msg.payload))
            return
        update(data)


print("connect MQTT..")
client = mqtt.Client()
client.on_connect = mqtt_connect
client.on_message = mqtt_message
client.connect("localhost", 1883, 60)
client.loop_forever()

# vim: set expandtab ts=4:
