
test:	generic pcur ptot pkwh

generic:
	@echo "----------------"
	@date
	@python3 test_ana_generic.py

pcur:
	@echo "----------------"
	@date
	@python3 test_ana_pcur.py

ptot:
	@echo "----------------"
	@date
	@python3 test_ana_ptot.py

pkwh:
	@echo "----------------"
	@date
	@python3 test_ana_pkwh.py
