name: UnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Perform Unit Tests
      run: |
        sudo apt-get install -y sendxmpp
        cd tests
        make 2&1 > /tmp/makelog
        if [ $? -eq 0 ]; then
                date > /tmp/makelog
                echo "Test PASS" >> /tmp/makelog
        fi
        cat /tmp/makelog | sendxmpp -u ${{ secrets.XMPPU }} -j ${{ secrets.XMPPD }}  -t -a /etc/ssl/certs/ -p ${{ secrets.XMPPPW }} ${{ secrets.XMPPREC }} 
