name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Perform Unit Tests
      run: |
        sudo apt-get install -y sendxmpp
        cd tests
        make | sendxmpp -u ${{ secrets.XMPPU }} -j ${{ secrets.XMPPD }}  -t -a /etc/ssl/certs/ -p ${{ secrets.XMPPPW }} ${{ secrets.XMPPREC }} 
